apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: jenkins-pipeline
spec:
  serviceAccountName: default
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest
      securityContext:
        runAsUser: 1000
      resources:
        requests:
          memory: "200Mi"
          cpu: "250m"
        limits:
          memory: "1000Mi"
          cpu: "1000m"
    # - name: terraform
    #   image: eu.gcr.io/mgmt-bak-tst-0d5f/platform_tools/terraform-tools:v0.23.0
    #   securityContext:
    #     runAsUser: 0
    #   command:
    #     - cat
    #   tty: true
    #   resources:
    #     requests:
    #       memory: "200Mi"
    #       cpu: "250m"
    #     limits:
    #       memory: "1000Mi"
    #       cpu: "1000m"